# Generated by Django 4.1 on 2022-08-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitems",
            options={"verbose_name_plural": "Order Items"},
        ),
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "Shipping Address"},
        ),
    ]
