# Generated by Django 4.1 on 2023-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_orderitems_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
